### ISSUE TITLE
Please add Topic 3 Network Type: Intranet

### ISSUE THREAD

**Issue by ib-teach** [bmackenty/computersciencewiki.org#72]
As students are still using this wiki, I suggest adding information about an overlooked network type: https://en.wikipedia.org/wiki/Intranet for the networking unit. I suggest adding it to this page: https://computersciencewiki.org/index.php?title=Types_of_networks

**Comment by bmackenty** [comment]
on it. I really appreciate the suggestion. Should be done by the end of the day today, I'd appreciate your feedback on the quality of the article. :-)

**Comment by bmackenty** [comment]
done. 
https://computersciencewiki.org/index.php?title=Types_of_networks
